services:
 db:
   image: postgres:17
   environment:
     POSTGRES_DB: ${DATABASE_NAME}
     POSTGRES_USER: ${DATABASE_USERNAME}
     POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
   ports:
     - ${DATABASE_PORT}:${DATABASE_PORT}
   volumes:
     - postgres_data:/var/lib/postgresql/data
   healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $DATABASE_USERNAME -p $DATABASE_PORT -d $DATABASE_NAME"]
      interval: 5s
      timeout: 5s
      retries: 10
   env_file:
     - .env
 
 django-web:
   build: .
   container_name: django-docker
   ports:
     - "8080:8080"
   depends_on:
    db:
      condition: service_healthy
   environment:
     DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
     DEBUG: ${DEBUG}
     DJANGO_LOGLEVEL: ${DJANGO_LOGLEVEL}
     DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
     DATABASE_ENGINE: ${DATABASE_ENGINE}
     DATABASE_NAME: ${DATABASE_NAME}
     DATABASE_USERNAME: ${DATABASE_USERNAME}
     DATABASE_PASSWORD: ${DATABASE_PASSWORD}
     DATABASE_HOST: ${DATABASE_HOST}
     DATABASE_PORT: ${DATABASE_PORT}
   env_file:
     - .env
volumes:
   postgres_data: